#############################################
#                                           #
# COMMON INFO : Site? ?? ???? ??   #
#                                           #
#############################################

# ?? ?? (0?? ?? ??? ??, ? ?? ?? ??)
LogWrite = 1

# ?? ?? ?? (???? ?? ??, ?: /usr/local/)
LogPath = /home/dooray/ServiceLinker_File/05_SCSLLog/

# ?? ??? (???? ';' ??, ???? ??)
FileExt = doc;docx;xls;xlsx;xlsm;ppt;pptx;hwp;hwpx;pdf;bmp;gif;jpg;jpeg;tif;tiff;csv;txt

# ? ?? ?? ?? ??? ID
ServiceID = 02

# ?? ??
LogFilter = ERROR; INFO; WARNING; DEBUG; LIB; keyfile; MEMORY;


################################################################################
#                                                                              #
# SECURE INFO : ??? ??? ?? ???? ?????.                       #
#                                                                              #
################################################################################

# authInfo API ?? ?? ?? (0: ???, 1: ??, ???: ???)
#useAuthInfo = 1

# ??? ?? ?? ID
#ExceptDecryptGradeID = 0000001;0000002;0000003;

# ??? ?? ?? - authInfo API ?? ? ?? (0: ??, 1: ??, ???: ???? ??)
# ??, ??, ??, SOM, ??, ??, ????, ???? (?: 01000000 - ?? ??? ??? ??? ??)
#DecryptAllowAuth = 00000000


################################################################################
#                                                                              #
# OPTIONAL INFO : ?? Site??? ???? ?????. ?? ?, ? ? ? ?? #
#                                                                              #
################################################################################

# BYPASS MODE (1?? Bypass, ? ?? ???)
#BypassMode = 1

# ??? ?? ??? ?? (0: ???, 1: ??, ???: ???)
#useServiceLinkerIcon = 1

# CACHE MODE (1?? Cache Mode, ? ?? ?? ??)
#nEncCache = 1

# Cache Mode?? ?? ??? ?? ?? ?? ?? ?? (???: 300)
#nMaxLoopCache = 300

# File I/O ?, ? ?? ????? ??? ?? (???: 65536, 1?? ? ?)
#FileBufferSize = 65536

# ??? ???? (???: AES, AES ??? ?? ??, DocumentVersion = 4? ??)
# ARIA ???? ?? ? DSHEADER_KEY ??(???? ?? DB?? ?? ??)
#Algorithm = ARIA

#ARIA_EXTEND = 1
#ARIA_EXTEND_PURE = 1
#DSHEADER_KEY = 2gkMmyUqQ1ZLGDDB

# ?? ??
#DocumentVersion = 4

# ANSI ????
#AnsiCharset = EUC-KR

# Key File ??? ?? ??? (0: ???, 1: ??, ???: ??)
#KeyFileOffset = 0

# ATELIB_PATH
#ATELIB_PATH = C:\\Dev\\Source\\Linker\\ServiceLinker\\src\\JavaServiceLinker\\5163??\\XecureATE\\win32\\XecureATE.dll

# AKS Server Info
#ServerIP = 10.10.10.10
#ServerPort = 62000

# ?? ?? ?? ?? (???? ?? ??, ?: /usr/local/)
#TransLogPath = C:/ServiceLinker/TransLog/

# IP? ?? ?? ????? windows ? ?? ??? ??
useWindowsKeyFile = 1

# DOC UID ?? ??
useAutoGenDocUID = 1

# ????? ServerID? null? ?? ???? ?? - 0:?????? / 1:????
#ServerIDNullPass = 1

# ?????? IP ?? ??? ?? ???
#KeyManagerAuthType = 1
# ?? ????? ?? ??
#HostnameMaxLength = 15

# ?/??? ? ???? ???? ?? ??
#NoSaveServerKeyToVfi = 1

useMasterKey = 1

bypassTimeCheck = 1
