#spring.application.name=OkfgDRMAdapter  # dooray-drm.spay.sginfra.net
application:
        title: OkfgDRMAdapter
        version: 1.0
spring:
  profiles:
    default: local
server:
    port: 9090

# Swagger ?? /swagger-ui/index.html
springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /docs
  packages-to-scan: com.okfg.drm.adapter.biz.controller
  paths-to-match: /v1/**

---
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  config:
    activate:
      on-profile: local
drm:
  testFile: "${user.dir}/src/main/resources/softcamp_local_test/testFiles/"
  softcampProperties: "${user.dir}/src/main/resources/softcamp_local_test/softcamp.properties"
  keyfilePath: "${user.dir}/src/main/resources/softcamp_local_test/keyDAC_SVR0.sc"
  fileExt: "FileExt"   # 지원 확장자 ( 구분자는 ';', 소문자를 사용 )
  defaultDomain: "SECURITYDOMAIN"
  defaultAuthBits: "111001100"
  groupId: "System"
  doorayFilePath: "${user.dir}/dooray/{seq}/"   # 상대경로 로컬 생성
  jwt:
    secret: "9386d7c69da34674a8f9dce6332c78b4c9b328af85ee02999c24509f94d74b1e"
    issuer: "spay"

---
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  config:
    activate:
      on-profile: dev
drm:
  testFile: "/home/dooray/app/adapter/testFiles/"
  softcampProperties: "/home/dooray/ServiceLinker_File/02_Module/02_ServiceLinker/softcamp.properties"
  keyfilePath: "/home/dooray/ServiceLinker_File/04_KeyFile/keyDAC_SVR0.sc"
  fileExt: "FileExt"   # 지원 확장자 ( 구분자는 ';', 소문자를 사용 )
  defaultDomain: "SECURITYDOMAIN"
  defaultAuthBits: "111001100"
  groupId: "System"
  doorayFilePath: "/home/dooray/app/adapter/{seq}/"
  jwt:
    secret: "e6a5516a62b9d1fe3145ff530fd0a8b3"
    #    secret: "9386d7c69da34674a8f9dce6332c78b4c9b328af85ee02999c24509f94d74b1e"
    issuer: "spay"

---
spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  config:
    activate:
      on-profile: prod
drm:
  testFile: "/home/dooray/app/adapter/testFiles/"
  softcampProperties: "/home/dooray/ServiceLinker_File/02_Module/02_ServiceLinker/softcamp.properties"
  keyfilePath: "/home/dooray/ServiceLinker_File/04_KeyFile/keyDAC_SVR0.sc"
  fileExt: "FileExt"   # 지원 확장자 ( 구분자는 ';', 소문자를 사용 )
  defaultDomain: "SECURITYDOMAIN"
  defaultAuthBits: "111001100"
  groupId: "System"
  doorayFilePath: "/home/dooray/app/adapter/{seq}/"
  jwt:
    secret: "e6a5516a62b9d1fe3145ff530fd0a8b3"
    #    secret: "9386d7c69da34674a8f9dce6332c78b4c9b328af85ee02999c24509f94d74b1e"
    issuer: "spay"